### ISSUE TITLE
Remove `create_discovery_method`

### ISSUE THREAD

**Issue by ikalnitsky** [sc68cal/Kostyor#54]
It seems like there's no use of this method, so let's get rid of this. We will implement discovery methods via some sort of extensions / drivers.

**Comment by sc68cal** [comment]
Sounds good

**Comment by jvarlamova** [comment]
Guys, would you mind if I work on this issue?

**Comment by ikalnitsky** [comment]
@jvarlamova nope. go ahead. :) thanks.

**Comment by jvarlamova** [comment]
https://github.com/sc68cal/Kostyor/pull/61
