### ISSUE TITLE
DB migration issue

### ISSUE THREAD

**Issue by jvarlamova** [sc68cal/Kostyor#76]
According to DB model, table 'upgrade_tasks' has column 'status', but it isn't created by migration. Need to bring model and actual state of DB into compliance.

**Comment by ikalnitsky** [comment]
It would be also great to have a test that checks that DB schema created by ORM is the same as DB schema created by Alembic.

**Comment by jvarlamova** [comment]
Also, upgrade task status value now can be one of the following list - https://github.com/sc68cal/Kostyor/blob/master/kostyor/common/constants.py#L16.

I'm afraid this list reflects cluster statuses, but not upgrade task state. It seems that for upgrade task we don't need 'READY_FOR_UPGRADE' and 'NOT_READY_FOR_UPGRADE', but we may add something like 'UPGRADE_FINISHED'. Guys, what do you think?

**Comment by jvarlamova** [comment]
@ikalnitsky Agree with you, such test will be useful.

**Comment by jvarlamova** [comment]
@sc68cal What do you think about tests to ensure that DB state matches model?

**Comment by jvarlamova** [comment]
@sc68cal Yes, it wasn't covered by our tests.

**Comment by jvarlamova** [comment]
https://github.com/sc68cal/Kostyor/pull/79
